# Generated by Django 5.0.2 on 2024-05-06 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estacione',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id_estación', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Facultade',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id_facultad', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('abrebiación', models.CharField(max_length=5)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id_sede', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('dirección', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id_programa', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('abrebiación', models.CharField(max_length=5)),
                ('id_facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parqueadero.facultade')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Punto',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id_punto', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(default=True)),
                ('codigo_punto', models.CharField(max_length=50)),
                ('id_estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parqueadero.estacione')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='estacione',
            name='id_sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parqueadero.sede'),
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id_usuario', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('código', models.CharField(max_length=50)),
                ('identificación', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('id_programas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parqueadero.programa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Parkine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id_parking', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('id_punto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parqueadero.punto')),
                ('id_usurio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parqueadero.usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
