# Generated by Django 5.0.2 on 2024-05-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parqueadero', '0004_alter_usuario_apellido_alter_usuario_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultade',
            name='abrebiación',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='programa',
            name='abrebiación',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='programa',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
